version: '3'
services:
        nginx:
                container_name: nginx
                build: ./requirements/nginx
                volumes:
                        - wordpress:/var/www/html
                ports:
                         - 443:443
                networks:
                         - network
                restart: always
        mariadb:
                image: mariadb
                volumes:
                        - mariadb:/var/lib/mysql
                networks:
                        - network
                ports:
                        - 3306:3306
                restart: always
                env_file:
                        - .env
        wordpress:
                container_name: wordpress
                build: ./requirements/wordpress
                volumes:
                        - wordpress:/var/www/html
                ports:
                        - 9000:9000
                networks:
                         - network
                restart: always
                env_file:
                        - .env
                depends_on:
                        - mariadb
                
volumes:
        mariadb: {}
        wordpress: {}
networks:
        network:
                driver: bridge