version: '3'

services:        
        mariadb:
                #container_name: mariadb
                #build: ./requirements/mariadb
                image: mariadb
                networks:
                        - inception_nw
                volumes: 
                        - /data/mariadb:/var/lib/mysql
                env_file:
                        - .env
                restart: always 
     

        wordpress:
                image: wordpress:php7.3-fpm-alpine
                networks:
                        - inception_nw
                volumes:
                        - /data/wordpress:/var/www/html
                depends_on:
                        - mariadb
                env_file:
                        - .env
                links:
                        - mariadb
                restart: always

        nginx:
                #container_name: nginx
                #build: ./requirements/nginx
                image: nginx
                depends_on:
                        - wordpress
                networks: 
                        - inception_nw
                volumes:
                        - /data/wordpress:/var/www/html
                ports:
                        - "443:443"
                links:
                        - wordpress
                restart: always

networks:
        inception_nw:

